all:
  vars:
    deploy_user: seiya
    ansible_user: "{{ deploy_user }}"
    project_root: "/home/{{ ansible_user }}/git/news_check"
    gemini_api_key: "AIzaSyAiErydai32rVKWdByg7kvPIvPLkWohe6Q"
    youtube_api_key: "AIzaSyCDZVcQeBBEzRHHqqQHXQXfBxh14OMXW-M"
    next_public_api_url: "http://localhost:8000"

  children:
    # ローカル環境 (WSL)
    local:
      hosts:
        localhost:
          ansible_connection: local

    # 本番環境 (OCI)
    prod:
      hosts:
        # TerraformのOutputからIPを取得してここに記載、または動的インベントリを利用
        oci_instance:
          ansible_host: 217.142.230.83
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
