all:
  children:
    news_check:
      hosts:
        # ここにデプロイ先のIPアドレスを記述してください
        # server1:
        #   ansible_host: 203.0.113.10
        #   ansible_user: ubuntu
        #   ansible_ssh_private_key_file: ~/.ssh/id_rsa
