---
- name: Deploy News Check Application
  hosts: all
  become: true

  vars:
    # project_root and project_repo are defined in inventory/group_vars
    # project_repo default can be kept here if common, but inventory specific is better
    github_user: "Seiya-Nakagawa"
    project_repo: "https://github.com/{{ github_user }}/news_check.git"

  roles:
    - common
    - docker
    - app_deploy
